sudo: required
dist: trusty
language: node_js

node_js:
    - "8.10.0"

before_install:
  - npm i -g npm

install:
  - npm ci

script:
    - npm run lint
    - npm run test
    - npm run cover

after_success:
    - npm run coveralls

email:
  recipients:
    - 929662659@qq.com
  on_success: never
  on_failure: always

