language: node_js

node_js:
    - "8.9.0"

install:
  - npm i

cache:
  directories:
    - "node_modules"

script:
    - npm run lint
    - npm run test

email:
  recipients:
    - 929662659@qq.com
  on_success: never
  on_failure: always

